import type { Meta, StoryObj } from "@storybook/react-vite";

const meta = { title: "Operations/Backoffice patterns", parameters: { layout: "padded" } } satisfies Meta;
export default meta;
type Story = StoryObj;

export const OverviewMetrics: Story = { render: () => <section className="ops-showcase"><p className="ops-kicker">Operations console · local edit</p><h2 className="ops-title">오늘의 운영 현황</h2><div className="ops-metrics">{[["123", "전체 콘텐츠"], ["109", "공개 반영 대상"], ["0", "미디어 에셋"], ["0", "누적 조회"]].map(([value, label]) => <div className="ops-metric" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></section> };

export const ContentPipeline: Story = { render: () => <section className="ops-showcase"><p className="ops-kicker">Pipeline</p><h2 className="ops-title">어디까지 왔는지</h2><div className="ops-board">{[["Draft", "원문을 다듬는 중", "11", "AI가 인용한 페이지와 AI가 추천한 브랜드는 다를 수 있다", "essay"], ["In process", "채널·미디어를 준비하는 중", "1", "콘텐츠를 개인화해도, 명제까지 바꾸면 안 된다", "essay"], ["Published", "발행 완료·공개 검토 대상", "111", "이 작업에 LLM까지 쓸 필요가 있었나", "framework"]].map(([stage, description, count, title, type]) => <section className="ops-column" key={stage}><header className="ops-column-header"><div><h3>{stage}</h3><p>{description}</p></div><b className="ops-column-count">{count}</b></header><article className="ops-card"><div className="ops-card-meta"><span>2026-08-02</span><b>{type}</b></div><h4>{title}</h4><p className="ops-card-tags">knowledge systems · reader path · article</p></article></section>)}</div></section> };

export const MarkdownEditor: Story = { render: () => <section className="ops-editor" aria-label="Markdown 편집 패턴"><header className="ops-editor-header"><div><p className="ops-kicker">Content file / local edit</p><h2>콘텐츠를 개인화해도, 명제까지 바꾸면 안 된다</h2></div><button className="ops-button" type="button">닫기</button></header><div className="ops-editor-toolbar"><div><button className="ops-button" type="button">미리보기</button><button className="ops-button is-active" type="button">Markdown 편집</button></div><button className="ops-button primary" type="button">로컬에 저장</button></div><textarea aria-label="Markdown 원고" defaultValue={'---\ntitle: "콘텐츠를 개인화해도, 명제까지 바꾸면 안 된다"\n---\n\n## 고정해야 하는 정보 단위\n\n독자 경로가 달라도, 명제와 근거는 보존한다.'} /></section> };
